const TXT = {
    TITLE: 'MEME VOTE SITE',
    HOT: 'HOT',
    REGULAR: 'REGULAR',
    FAVORITE: 'FAVORITE',
    MEME_FORM: 'MEME-FORM',
    MEME: 'MEME',
    MEMES: 'MEMES',
    NO_MEMES: 'There is no memes in this section.',
    SECTION_HOT: 'HOT MEMES',
    SECTION_REGULAR: 'REGULAR MEMES',
    SECTION_FAVORITE: 'FAVORITE MEMES',
    SECTION_MEME_FORM: 'MEME-FORM',
    LOCAL_STORAGE_NAME: 'MemesLS',
    REDUX_STORE_NAME_MEME: 'memes',
    REDUX_STORE_NAME_SECTION: 'sections',
    API_ADDRESS: 'http://localhost:3000/api/memes',
    ERROR_404: 'ERROR',
    ERROR_PATH: 'Wrong path.',
    FORM_MEM_TITLE: 'Meme title',
    FORM_MEM_URL: 'Paste URL (jpg or png)',
    FORM_PREVIEW_BUTTON: 'CLICK TO PREVIEW YOUR MEME',
    FORM_SUBMIT_BUTTON: 'CLICK TO SUBMIT YOUR MEME',
    FORM_ERROR: 'Something went wrong, check image url.',
}

export default TXT
